//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContraDescuento.GUI.Recurso.Keystore {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Keystore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keystore() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContraDescuento.GUI.Recurso.Keystore.Keystore", typeof(Keystore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;RSAKeyValue&gt;&lt;Modulus&gt;vIZ8CR55TZk5ct+wMNwsLwzNhWVH1ab7jCkkV/LjIcQu+ceMYkuQpj/i0LYxeMv40MgUeuecVEJBRMb9nmR1uHRUdtZPyxuuKkm4QtCR+sBF9xbJfn87mcRcFGZkK7rrA2lMk/faheuPLBdM0lYZQt04aG1ccXidKLNDMiCjP3U=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;53AxuX+krON6zmI3FESudw9MUJpKZEs72JK2n+8A8ryx0t3O35uU8zwfn3K+6Iky+SPsk5+ea/PaCZD4zblfSw==&lt;/P&gt;&lt;Q&gt;0IhqOP+cPkpTkoDKAF2kP0jdlVBjD+QxECeuUFPGc+rLGdip8MHYXiOjMP7n4X00fon/edHdYTJkeE0WT7LkPw==&lt;/Q&gt;&lt;DP&gt;oj1+PiGC2UfmcQNcxTKYcxIgV2ixubkbzOicaWVsbr1kkwO23/363sBJEsenmO+E8i4CzEHbFqYtNQORxvWqHQ==&lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string llave_privada {
            get {
                return ResourceManager.GetString("llave_privada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;RSAKeyValue&gt;&lt;Modulus&gt;vIZ8CR55TZk5ct+wMNwsLwzNhWVH1ab7jCkkV/LjIcQu+ceMYkuQpj/i0LYxeMv40MgUeuecVEJBRMb9nmR1uHRUdtZPyxuuKkm4QtCR+sBF9xbJfn87mcRcFGZkK7rrA2lMk/faheuPLBdM0lYZQt04aG1ccXidKLNDMiCjP3U=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string llave_publica {
            get {
                return ResourceManager.GetString("llave_publica", resourceCulture);
            }
        }
    }
}
